Repository FRONTENDSCHOOL7/Double-Check, pull requests merged in 2023-12, with the labels that each got.

#212 fix: 글귀 작성 페이지에서 나갈 시 내용이 저장되지 않게 수정 #211
  src/Pages/Phrase/PhraseEdit.jsx
  src/Pages/Phrase/PhraseUpdate.jsx
  src/Pages/Phrase/PhraseUpload.jsx
Labels: 은진, ⚡️fix

#214 fix: 피드 전체 목록의 api 수정 #213
  src/API/Post.js
Labels: 은진, ⚡️fix

#216 refactor: 검색 기능 최적화 #208
  src/API/Post.js
  src/Hooks/useDebounce.jsx
  src/Pages/Book/BookDetailPage.jsx
  src/Pages/LoginPage.jsx
  src/Pages/Phrase/PhraseEdit.jsx
  src/Pages/Post/PostDetailPage.jsx
  src/Pages/Post/PostEditPage.jsx
  src/Pages/Post/PostMain.jsx
  src/Pages/Post/PostPage.jsx
  src/Pages/ProfilePage.jsx
  src/Pages/SearchPage.jsx
  src/Pages/SetMyInfo.jsx
  src/components/BestItem/BestPost.jsx
  src/components/Common/Button/likeButton.jsx
  src/components/Common/NavBar/NavBar.jsx
  src/components/Common/NavBar/NavBarStyle.jsx
  src/components/Common/Topbar/Topbar.jsx
  src/components/Common/input.jsx
  src/components/MyProfile/FollowingList.jsx
  src/components/MyProfile/Profile.jsx
  src/components/Post/PostDetail.jsx
  src/components/Post/UserPost.jsx
  src/components/Search/SearchContent.jsx
Labels: 하연, ♻️ refactor, ⚡️fix

#219 fix: 프로필 수정 시 잘못된 경로 이동하는 버그 수정 #218
  src/Pages/SetMyInfo.jsx
Labels: 은진, ⚡️fix

#221 feat: 사용자별 글귀 목록 API 및 컴포넌트 구현 #220
  src/Hooks/usePhrase.js
  src/components/MyPhrase/MyPhraseList.jsx
Labels: 은진, feat

#223 fix: 글귀 작성을 완료했을 때 글귀 내용이 사라지는 버그 수정 #222
  src/Pages/Phrase/PhraseUpload.jsx
Labels: 은진, ⚡️fix

#228 fix: 다른 사용자의 프로필로 이동한 경우 데이터가 제대로 반영되지 않는 버그 수정
  src/Pages/ProfilePage.jsx
  src/components/Profile/Profile.jsx
Labels: 은진, ⚡️fix

#230 rename: 프로필 폴더 이름 변경
  src/components/Profile/FollowListStyle.jsx
  src/components/Profile/FollowerList.jsx
  src/components/Profile/FollowingList.jsx
Labels: 은진, ♻️ refactor

#232 fix: 피드 뒤로가기 버그 수정
  src/Pages/Post/PostDetailPage.jsx
  src/components/Post/PostItem.jsx
  src/components/Post/UserPost.jsx
Labels: 은진, ⚡️fix

#234 fix: 작성한 글귀가 없는 경우 스켈레톤을 적용하지 않도록 수정 #233
  src/components/MyPhrase/MyPhraseList.jsx
Labels: 은진, ⚡️fix

#235 fix: 스타일 컴포넌트 에러 수정 및 lazy loading 최적화
  src/Pages/Book/BookDetailPage.jsx
  src/Pages/Book/BookListPage.jsx
  src/Pages/Phrase/PhraseList.jsx
  src/Pages/Phrase/PhraseUpload.jsx
  src/Pages/Post/PostPage.jsx
  src/Pages/ProfilePage.jsx
  src/Pages/SetMyInfo.jsx
  src/Route/BookRoutes.jsx
  src/Styles/FeatureStyle.js
  src/components/Banner/BannerData.js
  src/components/Banner/BannerDot.jsx
  src/components/Banner/BannerSlideEffect.jsx
  src/components/Banner/BannerSlider.jsx
  src/components/BestItem/BestBook.jsx
  src/components/BestItem/BestBookItem.jsx
  src/components/BestItem/BestPost.jsx
  src/components/BestItem/BestPostItem.jsx
  src/components/Book/BookList.jsx
  src/components/BookSlide/BookSlide.jsx
  src/components/BookSlide/BookSlideItem.jsx
  src/components/Category.jsx
  src/components/Comment/CommentUpload.jsx
  src/components/Common/Textarea/TextareaStyle.jsx
  src/components/Common/Topbar/TopBarBtn.jsx
  src/components/Common/Topbar/Topbar.jsx
  src/components/MainTopBar.jsx
  src/components/MyPhrase/MyPhraseList.jsx
  src/components/Post/PostDetail.jsx
  src/components/Post/PostStyle.jsx
  src/components/Profile/Profile.jsx
  src/components/Search/SearchContent.jsx
Labels: 하연, ♻️ refactor, ⚡️fix

#238 style: 피드 뷰 버튼 아이콘 사이즈 변경 #237
  src/components/Common/Button/ViewToggleButton.jsx
Labels: 은진, 💅🏻 UI

#240 refactor: 팔로워 리스트, 팔로잉 리스트 navigate 수정 #239
  src/components/Profile/FollowerList.jsx
  src/components/Profile/FollowingList.jsx
Labels: 은진, ♻️ refactor

#242 rename: 컴포넌트 폴더 내 잘못된 파일명 수정
  src/Pages/SearchPage.jsx
  src/components/Common/input.jsx
  src/components/Login/Login.jsx
  src/components/Login/SignUp.jsx
Labels: 은진

#244 style: 글로벌스타일 폰트 파일 정리
  src/Styles/GlobalStyle.js
Labels: 은진, 💅🏻 UI

#246 refactor: 피드 상세페이지 더보기 버튼 텍스트 수정 #245
  src/components/Post/PostDetail.jsx
  src/components/Post/UserPost.jsx
Labels: 은진, ♻️ refactor

#248 feat: 로그인 페이지 내 체험하기 기능 추가 #247
  src/Pages/LoginPage.jsx
Labels: 은진, 💅🏻 UI, feat

#250 fix: 프로필 설정하기 버튼이 보이지 않는 버그 수정 #249
  src/Pages/ProfilePage.jsx
  src/components/Profile/Profile.jsx
Labels: 은진, ⚡️fix

#251 style: 도서 상세페이지 UI 변경
  src/Pages/Book/BookDetailPage.jsx
  src/Styles/LayoutStyle.js
  src/components/BestItem/BestBookItem.jsx
  src/components/Book/BookButtons.jsx
  src/components/Book/BookDetail.jsx
  src/components/Book/BookDetailDesc.jsx
  src/components/BookSlide/BookSlide.jsx
  src/components/BookSlide/BookSlideItem.jsx
  src/components/Common/Topbar/Topbar.jsx
  src/components/Search/SearchContent.jsx
Labels: 하연, 💅🏻 UI

#255 style: 시작페이지, 로그인 페이지 UI 변경 #254
  src/Pages/LoginPage.jsx
  src/Pages/StartLoginPage.jsx
  src/assets/images/icon/icon-checked.svg
  src/assets/images/icon/icon-unchecked.svg
Labels: 은진, 💅🏻 UI

#257 refactor: font preload로 성능 최적화 #256
  public/index.html
Labels: 은진, ♻️ refactor

#259 refactor: 코드 오타 수정 및 테스트페이지 삭제
  src/API/Post.js
  src/Pages/TestPage.jsx
  src/components/Common/Topbar/Topbar.jsx
Labels: 은진, ♻️ refactor

#261 feat: 회원가입 페이지 상단바 뒤로가기 기능 추가 #260
  src/Pages/SignupPage.jsx
  src/assets/images/logo/logo4.png
  src/assets/images/logo/logo6.svg
Labels: 은진, 💅🏻 UI, ♻️ refactor

#263 refactor: 사용자가 작성한 내용이 없는 경우 적절한 텍스트 제공 #262
  src/components/MyPhrase/MyPhraseList.jsx
  src/components/Post/UserPost.jsx
  src/components/Profile/Profile.jsx
Labels: 은진, ♻️ refactor

#265 feat: 파이어베이스 연결 및 도서 추천 수 구현 #264
  src/API/Firebase.js
  src/components/Book/AddBook.jsx
  src/components/Book/BookButtons.jsx
  src/firebase/config.js
Labels: 🔊 api 통신, 은진, feat

#266 refactor: 웹 접근성 및 불필요한 번들 사이즈 최적화
  package-lock.json
  package.json
  public/index.html
  src/Pages/ProfilePage.jsx
  src/Pages/SearchPage.jsx
  src/Pages/SetMyInfo.jsx
  src/Route/BookRoutes.jsx
  src/components/BestItem/BestBookItem.jsx
  src/components/BestItem/BestPostItem.jsx
  src/components/Book/BookButtons.jsx
  src/components/BookSlide/BookSlide.jsx
  src/components/BookSlide/BookSlideItem.jsx
  src/components/Common/Button/StarButton.jsx
  src/components/Common/HamSideBar/HamSideNoLogin.jsx
  src/components/Common/HamSideBar/HamSideYesLogin.jsx
  src/components/Common/HamSideBar/ToggleMenu.jsx
  src/components/Common/NavBar/NavBar.jsx
  src/components/Common/NavBar/NavBarStyle.jsx
  src/components/Common/Topbar/TopBarBtn.jsx
  src/components/Common/Topbar/Topbar.jsx
  src/components/MainTopBar.jsx
  src/components/ManuTab.jsx
Labels: 하연, ♻️ refactor

#267 style : 도서 상세페이지 스켈레톤 UI 추가
  package-lock.json
  package.json
  src/App.js
  src/Pages/Book/BookDetailPage.jsx
  src/Pages/LoginPage.jsx
  src/Pages/MainPage.jsx
  src/Pages/OthersPage.jsx
  src/Pages/StartLoginPage.jsx
  src/assets/Skeleton/BookDetailSkeleton.jsx
  src/assets/Skeleton/MainPostSkeleton.jsx
  src/assets/Skeleton/PostDetailSkeleton.jsx
  src/assets/Skeleton/PostSkeleton.jsx
  src/assets/Skeleton/UserProfileSkeleton.jsx
  src/components/BestItem/BestPost.jsx
  src/components/BestItem/BestPostItem.jsx
  src/components/Book/BookButtons.jsx
  src/components/Book/BookDetail.jsx
  src/components/Book/BookDetailDesc.jsx
  src/components/Common/Topbar/Topbar.jsx
  src/components/MainTopBar.jsx
Labels: 하연, 💅🏻 UI, ♻️ refactor

#270 fix : 도서 description에 HTML 엔티티 제거
  src/Pages/Book/BookDetailPage.jsx
  src/Pages/Book/BookListPage.jsx
  src/assets/Skeleton/MainSkeleton.jsx
  src/components/Book/BookDetail.jsx
  src/components/Book/BookList.jsx
Labels: 하연, 💅🏻 UI, ⚡️fix
