Repository FRONTENDSCHOOL7/Double-Check, pull requests merged in 2023-11, with the labels that each got.

#63 Style: 로그인,회원가입 PR등록
  package-lock.json
  package.json
  src/API/Profile.js
  src/App.js
  src/Pages/LoginPage.jsx
  src/Pages/MainPage.jsx
  src/Pages/SignupPage.jsx
  src/Recoil/Navbar.js
  src/assets/images/bg.png
Labels: 현석, 💅🏻 UI

#65 fix: 하단바 아이콘 변경 #64
  src/assets/images/icon/icon-fill-home.svg
  src/assets/images/icon/icon-fill-lookaround.svg
  src/assets/images/icon/icon-fill-profile.svg
  src/assets/images/icon/icon-fill-upload.svg
  src/assets/images/icon/icon-upload.svg
  src/assets/images/icon/show-more.svg
Labels: 은진

#67 fix: 상단바 컴포넌트 수정 #66
  src/Pages/Phrase/PhraseList.jsx
  src/components/Common/Button/Button.jsx
  src/components/Common/NavBar/NavBar.jsx
  src/components/Common/Topbar/Topbar.jsx
  src/components/EditPhrase/EditPhrase.jsx
  src/components/EditPhrase/EditPhraseStyle.jsx
Labels: 은진

#70 fix: 상단바 컴포넌트 수정 #69
  src/Pages/MainPage.jsx
  src/Pages/Phrase/PhraseUpdate.jsx
  src/Pages/Phrase/PhraseUpload.jsx
  src/Pages/SearchPage.jsx
  src/components/Common/Topbar/Topbar.jsx
Labels: 은진

#72 style: 벡터아이콘 추가 #71
  src/assets/images/icon/icon-comment.svg
  src/assets/images/icon/icon-fill-heart.svg
  src/assets/images/icon/icon-heart.svg
  src/assets/images/icon/show-more-y.svg
Labels: 은진

#74 fix: 글로벌 스타일, navbar 스타일 변경 #73
  src/Styles/GlobalStyle.js
  src/components/Common/NavBar/NabBarStyle.jsx
Labels: 은진

#76 [feat] 리뷰 전체보기 페이지 구현, 타임포맷 커스텀 훅 구현 #75
  src/API/post1.js
  src/App.js
  src/Hooks/useTimeSince.js
  src/Pages/Post/PostMain.jsx
  src/Recoil/Modal.js
  src/components/Post/Post.jsx
Labels: 은진

#78 Feat 게시물 작성페이지 구현
  src/API/Post.js
  src/App.js
  src/Pages/FeedPage.jsx
  src/Pages/PostPage.jsx
  src/Pages/post/PostDetailPage.jsx
  src/Pages/post/PostEditPage.jsx
  src/Pages/post/PostPage.jsx
  src/Recoil/PostDetail.js
  src/components/Banner/BannerData.js
  src/components/Book/BookDetail.jsx
  src/components/Book/BookList.jsx
  src/components/BookSlide/BookSlide.jsx
  src/components/BookSlide/BookSlideItem.jsx
  src/components/Common/Textarea/TextareaStyle.jsx
  src/components/Common/TopBar.jsx
Labels: 하연, feat

#80 [Style,feat]: SetMyProfile PR 등록
  src/Pages/MainPage.jsx
  src/Pages/SetMyInfo.jsx
  src/assets/images/default-img.png
  src/assets/images/icon/icon-img.png
  src/components/Category.jsx
  src/components/Common/TopBar.jsx
Labels: 🔊 api 통신, 현석, 💅🏻 UI

#82 fix: 상하단바 경로 및 아이콘 수정 #81
  src/assets/images/icon/icon-fill-home.svg
  src/assets/images/icon/icon-fill-post.svg
  src/assets/images/icon/icon-fill-upload.svg
  src/assets/images/icon/icon-home.svg
  src/assets/images/icon/icon-post.svg
  src/assets/images/icon/icon-upload.svg
  src/components/Common/NavBar/NavBar.jsx
  src/components/Common/NavBar/NavBarStyle.jsx
  src/components/Common/TopBar.jsx
  src/components/Common/Topbar/TopBarBtn.jsx
  src/components/Common/Topbar/Topbar.jsx
Labels: 은진

#84 fix: 모달 컴포넌트 수정 #83
  src/Hooks/useCustomToast.js
  src/components/Common/Modal/Modal.jsx
  src/components/Common/Modal/ModalStyle.jsx
Labels: 은진

#86 fix: 텍스트에어리어 컴포넌트 수정 #85
  src/components/Common/Textarea/Textarea.jsx
  src/components/Common/Textarea/TextareaStyle.jsx
Labels: 은진

#88 fix: 글귀 페이지 상단바 및 토스트 적용 #87
  src/Pages/Phrase/PhraseEditStyle.jsx
  src/Pages/Phrase/PhraseList.jsx
  src/Pages/Phrase/PhraseUpdate.jsx
  src/Pages/Phrase/PhraseUpload.jsx
Labels: 은진

#90 feat: 전체 피드 및 유저별 피드 컴포넌트 구현 #89
  src/API/post1.js
  src/App.js
  src/Hooks/usePhrase.js
  src/Hooks/useTimeSince.js
  src/Pages/MainPage.jsx
  src/Pages/Post/PostMain.jsx
  src/components/Post/Post.jsx
  src/components/Post/PostStyle.jsx
  src/components/Post/UserPost.jsx
Labels: 🔊 api 통신, 은진, feat

#92 style: 로그인페이지 스타일 적용 #91
  src/App.js
  src/Pages/StartLoginPage.jsx
  src/assets/images/LoginBackGround.svg
  src/assets/images/PigCharacter.png
Labels: 창영

#94 feat : 로그인 유무에 따라 열려야하는 사이드바 구현 #93
  .eslintrc.json
  src/App.js
  src/Pages/MainPage.jsx
  src/assets/images/doublechaeklogo.svg
  src/components/Common/Button/ButtonStyle.jsx
  src/components/Common/HamSideBar/HamSideNoLogin.jsx
  src/components/Common/HamSideBar/HamSideYesLogin.jsx
  src/components/Common/HamSideBar/ToggleMenu.jsx
Labels: 창영

#95 Style,feat/splash(style) signup(feat) PR등록
  src/App.js
  src/Pages/Post/PostDetailPage.jsx
  src/Pages/Post/PostEditPage.jsx
  src/Pages/Post/PostPage.jsx
  src/Pages/SignupPage.jsx
  src/Pages/SplashPage.jsx
  src/assets/images/bg/bg-space.jpeg
  src/assets/images/bg/bg-start.jpeg
  src/assets/images/character/dbc-book.svg
  src/assets/images/character/dbc.svg
  src/assets/images/character/dbc2.svg
  src/assets/images/character/dbc3.svg
  src/assets/images/logo/logo-white.svg
  src/components/Common/Textarea/TextareaStyle.jsx
Labels: 🔊 api 통신, 현석, 💅🏻 UI

#97 feat: 게시물 상세페이지에 모달,좋아요 기능 추가
  src/API/like.js
  src/App.js
  src/Pages/Post/PostDetailPage.jsx
  src/Pages/Post/PostPage.jsx
  src/components/Common/Button/likeButton.jsx
  src/components/Common/TopBar.jsx
  src/components/Common/Topbar/Topbar.jsx
  src/components/Post/PostDetail.jsx
Labels: 🔊 api 통신, 하연, feat

#99 style: 공통 컴포넌트 버튼, 하단바 수정 및 아이콘 추가 #98
  src/assets/images/icon/show-more-x.svg
  src/components/Common/Button/ButtonStyle.jsx
  src/components/Common/NavBar/NavBarStyle.jsx
Labels: 은진, 💅🏻 UI

#103 feat: 댓글 컴포넌트 구현
  src/API/Comment.js
  src/Recoil/CommentText.js
  src/components/Comment/CommentItem.jsx
  src/components/Comment/CommentUpload.jsx
  src/components/Comment/Comments.jsx
Labels: 🔊 api 통신, 은진, 💅🏻 UI

#108 style: 로그인 페이지 스타일 변경 #107
  src/Pages/LoginPage.jsx
  src/assets/images/bg/bg-white-space.svg
  src/components/Common/Button/ButtonStyle.jsx
Labels: 은진, 💅🏻 UI

#110 style: 댓글텍스트에어리어 스크롤바 숨김
  src/components/Comment/CommentUpload.jsx
Labels: 은진, 💅🏻 UI

#111 feat: 피드 상세페이지 신고기능 및 책 경로 설정
  src/Pages/Post/PostDetailPage.jsx
  src/Pages/Post/PostEditPage.jsx
  src/Pages/Post/PostMain.jsx
  src/Pages/Post/PostPage.jsx
  src/Pages/SearchPage.jsx
  src/Pages/SetMyInfo.jsx
  src/Recoil/UserInfo.js
  src/components/Banner/BannerData.js
  src/components/BookSlide/BookSlide.jsx
  src/components/BookSlide/BookSlideItem.jsx
  src/components/Common/HamSideBar/HamSideNoLogin.jsx
  src/components/Common/HamSideBar/HamSideYesLogin.jsx
  src/components/Post/Post.jsx
  src/components/Post/PostDetail.jsx
Labels: 하연, feat

#114 fix: 댓글 수 최신 상태로 반영 #113
  src/API/Comment.js
  src/Recoil/CommnetCount.js
  src/components/Comment/CommentItem.jsx
  src/components/Comment/CommentUpload.jsx
  src/components/Comment/Comments.jsx
Labels: 은진, 💅🏻 UI

#116 fix: 피드 목록 댓글 수 추가 및 스타일 변경 #115
  src/components/Post/Post.jsx
  src/components/Post/PostDetail.jsx
Labels: 은진, 💅🏻 UI

#117 style: 404, 스플래쉬 스타일 구현 PR 등록
  src/App.js
  src/Pages/ErrorPage.jsx
  src/Pages/SplashPage.jsx
  src/Pages/TestPage.jsx
  src/assets/images/404.svg
  src/assets/images/bg/bg-404.svg
  src/assets/images/bg/bg-error.svg
  src/components/Post/Post.jsx
  src/components/Post/PostDetail.jsx
Labels: 현석, 💅🏻 UI

#118 Fix: setMyProfile PR등록
  src/Pages/SetMyInfo.jsx
  src/components/Category.jsx
Labels: 현석, feat

#119 style: PR등록
  src/Pages/SetMyInfo.jsx
Labels: 현석, 💅🏻 UI

#121 style: 뷰 아이콘 추가
  src/assets/images/icon/icon-feed.svg
  src/assets/images/icon/icon-gallery.svg
Labels: 은진

#123 fix: 댓글 더보기 모달 구현
  src/components/Comment/CommentItem.jsx
  src/components/Comment/CommentUpload.jsx
Labels: 은진

#125 style: 사이드바 위치 조정 #124
  src/components/Common/HamSideBar/HamSideYesLogin.jsx
Labels: 은진

#127 fix: 전체 피드 모달 구현 및 댓글 수 적용 # 126
  src/API/Post.js
  src/App.js
  src/Pages/ErrorPage.jsx
  src/Pages/Post/PostDetailPage.jsx
  src/Pages/Post/PostEditPage.jsx
  src/Pages/Post/PostMain.jsx
  src/Pages/SetMyInfo.jsx
  src/Pages/SplashPage.jsx
  src/Pages/TestPage.jsx
  src/assets/images/404.svg
  src/assets/images/bg/bg-404.svg
  src/assets/images/bg/bg-error.svg
  src/components/Category.jsx
  src/components/Post/PostDetail.jsx
  src/components/Post/PostGallery.jsx
  src/components/Post/PostItem.jsx
  src/components/Post/UserPost.jsx
Labels: 은진

#129 fix: 포스트컴포넌트 수정
  src/assets/images/icon/icon-feed.png
  src/components/Post/PostItem.jsx
Labels: 은진

#130 feat/ Login상태에 따른 Route PR등록
  src/App.js
  src/components/Common/ ProtectedRoute/RouteModal.jsx
Labels: 현석, 💅🏻 UI, feat

#131 fix: 로그아웃, 로그인했을 때 메인페이지 새로고침(토큰 값 변경될때 랜더링) PR등록
  src/Pages/LoginPage.jsx
  src/components/Common/HamSideBar/HamSideYesLogin.jsx
Labels: 현석

#133 feat : myprofilepage 구현 #132
  src/App.js
  src/Pages/MyProfilePage.jsx
  src/components/Common/NavBar/NavBar.jsx
  src/components/MyProfile/Feed.jsx
  src/components/MyProfile/FollowerList.jsx
  src/components/MyProfile/FollowingList.jsx
  src/components/MyProfile/MyProfile.jsx
Labels: 창영

#135 fix: 포스트 api 통합 #134
  src/API/Post.js
  src/API/post1.js
  src/Pages/Post/PostMain.jsx
  src/components/Post/PostDetail.jsx
  src/components/Post/PostItem.jsx
  src/components/Post/UserPost.jsx
Labels: 🔊 api 통신, 은진

#136 Fix: 파일명 오류 수정 PR 등록
  src/App.js
  src/components/Common/ProtectedRoute/RouteModal.jsx
Labels: 현석

#137 feat: 스켈레톤 UI 추가
  package-lock.json
  package.json
  src/API/post1.js
  src/Hooks/useCustomToast.js
  src/Pages/Book/BookDetailPage.jsx
  src/Pages/Book/BookListPage.jsx
  src/Pages/MainPage.jsx
  src/Pages/Phrase/PhraseList.jsx
  src/Pages/Post/PostDetailPage.jsx
  src/Pages/Post/PostMain.jsx
  src/Pages/Post/PostPage.jsx
  src/Pages/SearchPage.jsx
  src/assets/Skeleton/BookListSkeleton.jsx
  src/assets/Skeleton/MainSkeleton.jsx
  src/assets/Skeleton/PhraseListSkeleton.jsx
  src/assets/Skeleton/PostDetailSkeleton.jsx
  src/components/BookSlide/BookSlide.jsx
  src/components/BookSlide/BookSlideItem.jsx
  src/components/Common/Loading.jsx
  src/components/Post/PostDetail.jsx
  src/components/Post/PostItem.jsx
Labels: 하연, 💅🏻 UI, feat

#140 feat: 경로 수정
  src/App.js
  src/Pages/ErrorPage.jsx
  src/Pages/LoginPage.jsx
  src/Pages/MainPage.jsx
  src/Pages/MyProfilePage.jsx
  src/Pages/Phrase/PhraseUpdate.jsx
  src/Pages/Post/PostDetailPage.jsx
  src/Pages/Post/PostPage.jsx
  src/Pages/SplashPage.jsx
  src/Pages/StartLoginPage.jsx
  src/Route/BookRoutes.jsx
  src/assets/images/404.svg
  src/assets/images/bg/bg-404.svg
  src/assets/images/bg/bg-error.svg
  src/components/Banner/BannerSlider.jsx
  src/components/BookSlide/BookSlide.jsx
  src/components/Common/HamSideBar/HamSideYesLogin.jsx
  src/components/Common/NavBar/NavBar.jsx
  src/components/Common/ProtectedRoute/RouteModal.jsx
  src/components/Common/TopBar.jsx
  src/components/Common/Topbar/Topbar.jsx
  src/components/MyProfile/FollowerList.jsx
  src/components/MyProfile/FollowingList.jsx
  src/components/Post/PostDetail.jsx
Labels: 하연, feat

#142 Fix : set my profile PR등록
  src/App.js
  src/Pages/SetMyInfo.jsx
  src/components/Category.jsx
Labels: 현석, feat

#144 fix: 공통 컴포넌트 수정 및 피드 뷰 아톰 구현 #143
  src/Recoil/FeedView.js
  src/components/Common/Button/ButtonStyle.jsx
  src/components/Common/Button/ViewToggleButton.jsx
  src/components/Common/NavBar/NavBar.jsx
Labels: 은진, 💅🏻 UI

#146 fix: 팔로잉 팔로워 리스트 수정, 팔로우 기능 구현
  src/API/Profile.js
  src/App.js
  src/Pages/MyProfilePage.jsx
  src/Pages/ProfilePage.jsx
  src/Recoil/Accountname.js
  src/components/MyProfile/Feed.jsx
  src/components/MyProfile/FollowListStyle.jsx
  src/components/MyProfile/FollowerList.jsx
  src/components/MyProfile/FollowingList.jsx
  src/components/MyProfile/MyProfile.jsx
  src/components/MyProfile/Profile.jsx
  src/components/Post/UserPost.jsx
Labels: 🔊 api 통신, 은진

#148 fix: 프로필 라우터 수정
  src/App.js
  src/Pages/ProfilePage.jsx
  src/components/Post/PostDetail.jsx
Labels: 은진

#149 style: set my profile PR등록
  src/Pages/SetMyInfo.jsx
Labels: 현석, 💅🏻 UI

#151 fix: post 경로 수정
  src/Pages/Post/PostMain.jsx
  src/components/Post/PostGallery.jsx
  src/components/Post/PostItem.jsx
  src/components/Post/UserPost.jsx
Labels: 🐛 bug, 🔊 api 통신, 하연

#152 fix: signup PR 등록
  src/App.js
  src/Pages/SignupPage.jsx
  src/components/Common/HamSideBar/HamSideNoLogin.jsx
Labels: 현석, feat

#154 fix: 피드 수정페이지 수정 #153
  src/Pages/Post/PostDetailPage.jsx
  src/components/Post/PostItem.jsx
Labels: 은진

#155 fix: category PR등록
  src/Pages/SetMyInfo.jsx
  src/components/Category.jsx
Labels: 현석

#159 fix: 사용자와 작성자 비교 및 모달 경로 이동 #158
  src/API/post1.js
  src/Pages/Phrase/PhraseList.jsx
  src/atoms/modal.js
  src/components/Comment/CommentItem.jsx
  src/components/Common/Modal/Modal.jsx
Labels: 은진

#161 style: 버튼 스타일 수정 및 프로필 하단바 atom 추가 #160
  src/Pages/ProfilePage.jsx
  src/components/Common/Button/ButtonStyle.jsx
Labels: 은진

#163 fix: 모달 경로 수정
  src/components/Common/Modal/Modal.jsx
Labels: 은진

#172 style: 프로필 스타일 수정 #171
  src/Pages/ProfilePage.jsx
  src/components/MyProfile/FollowingList.jsx
  src/components/MyProfile/Profile.jsx
Labels: 은진

#175 docs: 리드미 프로젝트 소개, 주요기능, 트러블 슈팅 내용 추가
  README.md
Labels: 은진

#179 fix : title명 수정 및 불필요한 모듈 삭제
  package-lock.json
  package.json
  public/index.html
Labels: 하연

#182 refactor: 상단바 중복 컴포넌트 제거 후 경로 수정 #181
  src/Pages/LoginPage.jsx
  src/components/Book/BookDetail.jsx
  src/components/Common/HamSideBar/HamSideYesLogin.jsx
  src/components/Common/NavBar/NavBar.jsx
  src/components/Common/NavBar/NavBarStyle.jsx
  src/components/Common/TopBar.jsx
  src/components/Common/Topbar/Topbar.jsx
Labels: 은진, 💅🏻 UI, ♻️ refactor

#185 refactor: splash이미지 로고 수정 PR등록
  src/Pages/SplashPage.jsx
  src/assets/images/logo/logo-white2.svg
Labels: 현석, 💅🏻 UI, ♻️ refactor

#187 fix: 도서 리스트명 수정 및 책 클릭시 해당 상세 페이지로 이동하게 수정
  README.md
  src/Pages/Book/BookListPage.jsx
  src/Pages/Book/BookMainPage.jsx
  src/Pages/MainPage.jsx
  src/assets/images/hamlogo.svg
  src/components/Book/BookDetail.jsx
  src/components/BookSlide/BookSlide.jsx
  src/components/BookSlide/BookSlideItem.jsx
  src/components/Common/HamSideBar/HamSideNoLogin.jsx
  src/components/Common/HamSideBar/HamSideYesLogin.jsx
Labels: 하연, ♻️ refactor, ⚡️fix

#192 refactor: 글귀 작성, 수정 뒤로가기 모달 추가 #191
  src/Pages/Phrase/PhraseUpdate.jsx
  src/Pages/Phrase/PhraseUpload.jsx
Labels: 은진, ♻️ refactor

#194 refactor: 피드 뒤로가기 모달 추가 및 버튼 비활성화 #193
  src/Pages/Post/PostEditPage.jsx
  src/Pages/Post/PostPage.jsx
Labels: 은진, ♻️ refactor

#196 style: 모달 텍스트 간격 변경 #195
  src/components/Common/Modal/ModalStyle.jsx
Labels: 은진, 💅🏻 UI

#199 refactor: 팔로우리스트, 팔로잉리스트 Loading 수정
  src/components/MyProfile/FollowListStyle.jsx
  src/components/MyProfile/FollowerList.jsx
  src/components/MyProfile/FollowingList.jsx
Labels: 은진, ♻️ refactor, ⚡️fix

#201 refactor: 프로필페이지 팔로우, 언팔로우 버튼 수정 #200
  src/Pages/ProfilePage.jsx
  src/components/MyProfile/Profile.jsx
Labels: 은진, ♻️ refactor, ⚡️fix

#203 refactor: 글귀 수정 페이지 버튼 수정 및 글귀 작성 시 입력 유효성 검사 수정 #202
  src/Pages/Phrase/PhraseUpdate.jsx
  src/Pages/Phrase/PhraseUpload.jsx
Labels: 은진, ♻️ refactor, ⚡️fix

#205 style: disabled 상태의 버튼 스타일 수정 #204
  src/components/Common/Button/ButtonStyle.jsx
Labels: 은진, 💅🏻 UI

#207 fix: 책 상세 정보 및 검색 정보 API 호출 시 발생한 예외 처리 수정
  src/Pages/Book/BookDetailPage.jsx
  src/Pages/Post/PostDetailPage.jsx
  src/Pages/SearchPage.jsx
  src/components/Book/BookDetail.jsx
  src/components/Book/BookList.jsx
  src/components/Post/PostDetail.jsx
  src/components/Search/SearchContent.jsx
Labels: 하연, ⚡️fix
