Repository FRONTENDSCHOOL7/Double-Check, pull requests merged in 2023-10, with the labels that each got.

#6 Feat : 기본 페이지 , 컴포넌트 세팅 & 책 페이지 추가
  .eslintrc.js
  .eslintrc.json
  jsconfig.json
  package-lock.json
  package.json
  server.js
  src/API/User.js
  src/App.js
  src/Pages/Book/BookDetailPage.jsx
  src/Pages/Book/BookListPage.jsx
  src/Pages/ErrorPage.jsx
  src/Pages/FeedEditPage.jsx
  src/Pages/FeedPage.jsx
  src/Pages/LoginPage.jsx
  src/Pages/MainPage.jsx
  src/Pages/SearchPage.jsx
  src/Pages/SignupPage.jsx
  src/Pages/SplashPage.jsx
  src/Route/BookRoutes.jsx
  src/Styles/GlobalStyle.js
  src/atoms/user.js
  src/components/Banner.jsx
  src/components/Book/BookDetail.jsx
  src/components/Book/BookList.jsx
  src/components/Common/BottomBar.jsx
  src/components/Common/Loading.jsx
  src/components/Common/TopBar.jsx
  src/components/Login/Login.jsx
  src/components/Login/SignUp.jsx
  src/components/Search/SearchContent.jsx
  src/components/Search/SearchInput.jsx
  src/index.js
Labels: enhancement, help wanted

#18 Feat: 로그인, 회원가입, 로그아웃
  .env
  .eslintrc.js
  .gitignore
  package-lock.json
  package.json
  src/API/Instance.js
  src/API/Profile.js
  src/API/User.js
  src/App.js
  src/Pages/Book/BookDetailPage.jsx
  src/Pages/Book/BookListPage.jsx
  src/Pages/LoginPage.jsx
  src/Pages/MainPage.jsx
  src/Pages/SignupPage.jsx
  src/Pages/TestPage.jsx
  src/Recoil/Accountname.js
  src/Recoil/LoginCheck.js
  src/Recoil/LoginToken.js
  src/Route/BookRoutes.jsx
  src/Search.js
  src/Styles/GlobalStyle.js
  src/Styles/GlobalStyles.js
  src/atoms/user.js
  src/components/Common/Button/Button.jsx
  src/components/Common/Button/ButtonList.jsx
  src/components/Common/Button/ButtonStyle.jsx
  src/components/Login/Login.jsx
  src/components/Login/SignUp.jsx
  src/index.js
Labels: 🔊 api 통신, 현석

#46 feat: profile PR 등록
  .env
  .gitignore
  package-lock.json
  package.json
  src/API/ImageUpload.js
  src/API/Instance.js
  src/API/Profile.js
  src/App.js
  src/Pages/LoginPage.jsx
  src/Pages/Phrase/PhraseList.jsx
  src/Pages/SetMyInfo.jsx
  src/Pages/TestPage.jsx
  src/Search.js
  src/components/Banner.jsx
  src/components/Common/Button/ButtonList.jsx
  src/components/Search/SearchInput.jsx
  test.txt
Labels: 🔊 api 통신, 현석

#48 style : 책 목록페이지 스타일 끝!
  package-lock.json
  package.json
  src/API/Profile.js
  src/App.js
  src/Pages/ OthersPage.jsx
  src/Pages/Book/BookDetailPage.jsx
  src/Pages/Book/BookListPage.jsx
  src/Pages/Phrase/PhraseList.jsx
  src/Pages/Phrase/PhraseWrite.jsx
  src/Styles/FeatureStyle.js
  src/Styles/GlobalStyle.js
  src/assets/images/logo/logo.svg
  src/assets/images/logo/logo1.svg
  src/assets/images/logo/logo2.svg
  src/assets/images/logo/logo3.svg
  src/components/Banner/BannerData.js
  src/components/Banner/BannerSlider.jsx
  src/components/Book/BookDetail.jsx
  src/components/Book/BookList.jsx
  src/components/BookSlide/BookSlide.jsx
  src/components/BookSlide/BookSlideItem.jsx
  src/components/Common/TopBar.jsx
  src/components/Common/TopBarBtn.jsx
  src/components/EditPhrase/EditPhrase.jsx
  src/components/Search/SearchContent.jsx
Labels: 하연, 💅🏻 UI

#50 style : 별 모양 저장 버튼 추가 , 팝업 추가
  package-lock.json
  package.json
  src/Pages/Book/BookDetailPage.jsx
  src/Styles/FeatureStyle.js
  src/components/Banner.jsx
  src/components/Book/BookDetail.jsx
  src/components/Book/BookList.jsx
  src/components/BookSlide/BookSlide.jsx
  src/components/BookSlide/BookSlideItem.jsx
  src/components/Common/Button/StarButton.jsx
  src/components/Common/NavBar/NabBarStyle.jsx
  src/components/Common/Toast/CustomToast.jsx
  src/components/Common/TopBar.jsx
  src/components/Common/TopBarBtn.jsx
Labels: 🐛 bug, 하연, 💅🏻 UI
